/// Flutter icons AppIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///
// coverage:ignore-file
// ignore_for_file: type=lint

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons();

  static const _kFontFam = 'app_icons';
  static const String? _kFontPkg = null;

  IconData
      add_1__expand_cross_buttons_button_more_remove_plus_add___mathematics_math =
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData add_bell_notification__notification_alarm_alert_bell_add =
      const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      add_circle__button_remove_cross_add_buttons_plus_circle___mathematics_math =
      const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData add_layer_2__layer_add_design_plus_layers_square_box =
      const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      add_square__square_remove_cross_buttons_add_plus_button___mathematics_math =
      const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData alarm_clock__time_tock_stopwatch_measure_clock_tick =
      const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData align_back_1__back_design_layer_layers_pile_stack_arrange_square =
      const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      align_center__text_alignment_align_paragraph_centered_formatting_center =
      const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData align_front_1__design_front_layer_layers_pile_stack_arrange_square =
      const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData align_left__paragraph_text_alignment_align_left_formatting_right =
      const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      align_right__rag_paragraph_text_alignment_align_right_formatting_left =
      const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData ampersand =
      const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData archive_box__box_content_banker_archive_file =
      const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      arrow_bend_left_down_2__arrow_bend_curve_change_direction_left_to_down =
      const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      arrow_bend_right_down_2__arrow_bend_curve_change_direction_right_to_down =
      const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_crossover_down__cross_move_over_arrow_arrows_down =
      const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_crossover_left__cross_move_over_arrow_arrows_left =
      const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_crossover_right__cross_move_over_arrow_arrows_ight =
      const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_crossover_up__cross_move_over_arrow_arrows_right =
      const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_cursor_1__mouse_select_cursor =
      const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_cursor_2__mouse_select_cursor =
      const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      arrow_curvy_up_down_1__both_direction_arrow_curvy_diagram_zigzag_vertical =
      const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_curvy_up_down_2 =
      const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_down_2__down_move_arrow_arrows =
      const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_down_dashed_square__arrow_keyboard_button_down_square_dashes =
      const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_expand__expand_small_bigger_retract_smaller_big =
      const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_infinite_loop__arrow_diagram_loop_infinity_repeat =
      const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_move__move_button_arrows_direction =
      const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      arrow_reload_horizontal_1__arrows_load_arrow_sync_square_loading_reload_synchronize =
      const IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_reload_horizontal_2 =
      const IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      arrow_reload_vertical_1__arrows_load_arrow_sync_square_loading_reload_synchronize =
      const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_reload_vertical_2 =
      const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_roadmap =
      const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_round_left__diagram_round_arrow_left =
      const IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_round_right__diagram_round_arrow_right =
      const IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_shrink__expand_retract_shrink_bigger_big_small_smaller =
      const IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      arrow_shrink_diagonal_1__expand_retract_shrink_bigger_big_small_smaller =
      const IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      arrow_shrink_diagonal_2__expand_retract_shrink_bigger_big_small_smaller =
      const IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      arrow_transfer_diagonal_1__arrows_arrow_server_data_diagonal_internet_transfer_network =
      const IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      arrow_transfer_diagonal_2__arrows_arrow_server_data_diagonal_internet_transfer_network =
      const IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      arrow_transfer_diagonal_3__arrows_arrow_server_data_diagonal_internet_transfer_network =
      const IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_up_1__arrow_up_keyboard =
      const IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData arrow_up_dashed_square__arrow_keyboard_button_up_square_dashes =
      const IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData ascending_number_order =
      const IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData attribution =
      const IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData auto_flash =
      const IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData backpack__bag_backpack_school_baggage_cloth_clothing_accessories =
      const IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData bag_suitcase_2__product_business_briefcase =
      const IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData blank_calendar__blank_calendar_date_day_month_empty =
      const IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData blank_notepad__content_notes_book_notepad_notebook =
      const IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData block_bell_notification__notification_alarm_alert_bell_block =
      const IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData bomb__delete_bomb_remove =
      const IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData book_reading__book_reading_learning =
      const IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData bookmark__bookmarks_tags_favorite =
      const IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData braces_circle__interface_math_braces_sign_mathematics =
      const IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      brightness_1__bright_adjust_brightness_adjustment_sun_raise_controls =
      const IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      brightness_2__bright_adjust_brightness_adjustment_sun_raise_controls_half =
      const IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      brightness_3__bright_adjust_brightness_adjustment_sun_raise_controls_dot_small =
      const IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData broken_link_2__break_broken_hyperlink_link_remove_unlink_chain =
      const IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData bullet_list__points_bullet_unordered_list_lists_bullets =
      const IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData business_card__name_card_business_information_money_payment =
      const IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData business_handshake__deal_contract_business_money_payment_agreement =
      const IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData business_user_curriculum =
      const IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      button_fast_forward_1__button_controls_fast_forward_movies_television_video_tv =
      const IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      button_fast_forward_2__button_controls_fast_forward_movies_television_video_tv =
      const IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      button_next__button_television_buttons_movies_skip_next_video_controls =
      const IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      button_pause_2__button_television_buttons_movies_tv_pause_video_controls =
      const IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      button_play__button_television_buttons_movies_play_tv_video_controls =
      const IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData button_power_1__power_button_on_off =
      const IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      button_previous__button_television_buttons_movies_skip_previous_video_controls =
      const IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      button_record_3__button_television_buttons_movies_record_tv_video_controls =
      const IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      button_rewind_1__rewind_television_button_movies_buttons_tv_video_controls =
      const IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      button_rewind_2__rewind_television_button_movies_buttons_tv_video_controls =
      const IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      button_stop__button_television_buttons_movies_stop_tv_video_controls =
      const IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData calendar_add__add_calendar_date_day_month =
      const IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData calendar_edit__calendar_date_day_compose_edit_note =
      const IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData calendar_jump_to_date =
      const IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData calendar_star__calendar_date_day_favorite_like_month_star =
      const IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData camera_1__photos_picture_camera_photography_photo_pictures =
      const IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      camera_disabled__photos_picture_camera_photography_photo_pictures_disabled_off =
      const IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      camera_square__photos_picture_camera_photography_photo_pictures_frame_square =
      const IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData celsius__degrees_temperature_centigrade_celsius_degree_weather =
      const IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chair__chair_business_product_comfort_decoration_sit_furniture =
      const IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chat_bubble_oval__messages_message_bubble_chat_oval =
      const IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      chat_bubble_oval_notification__messages_message_bubble_chat_oval_notify_ping =
      const IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chat_bubble_text_square__messages_message_bubble_text_square_chat =
      const IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chat_bubble_typing_oval__messages_message_bubble_typing_chat =
      const IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      chat_two_bubbles_oval__messages_message_bubble_chat_oval_conversation =
      const IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData check__check_form_validation_checkmark_success_add_addition_tick =
      const IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      check_square__check_form_validation_checkmark_success_add_addition_box_square_tick =
      const IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chevron_down =
      const IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chevron_left =
      const IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chevron_right =
      const IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData chevron_up =
      const IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData circle__geometric_circle_round_design_shape_shapes_shape =
      const IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData circle_clock__clock_loading_measure_time_circle =
      const IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData class_lesson__class_lesson_education_teacher =
      const IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData clipboard_add__edit_task_edition_add_clipboard_form =
      const IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      clipboard_check__checkmark_edit_task_edition_checklist_check_success_clipboard_form =
      const IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData clipboard_remove__edit_task_edition_remove_delete_clipboard_form =
      const IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData cloud__cloud_meteorology_cloudy_overcast_cover_weather =
      const IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData cog__work_loading_cog_gear_settings_machine =
      const IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData collaborations_idea__collaborations_idea_work =
      const IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData copy_paste__clipboard_copy_cut_paste =
      const IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData crop_selection__artboard_crop_design_image_picture =
      const IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData crown__reward_social_rating_media_queen_vip_king_crown =
      const IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData cursor_click =
      const IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData customer_support_1__customer_headset_help_microphone_phone_support =
      const IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData dashboard_circle__app_application_dashboard_home_layout_circle =
      const IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData definition_search_book =
      const IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      delete_1__remove_add_button_buttons_delete_cross_x_mathematics_multiply_math =
      const IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData delete_keyboard =
      const IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      desktop_chat__bubble_chat_customer_service_conversation_display_device =
      const IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      disable_bell_notification__disable_silent_notification_off_silence_alarm_bell_alert =
      const IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData download_file =
      const IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData earth_1__planet_earth_globe_world =
      const IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData edit_image_photo =
      const IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData empty_clipboard__work_plain_clipboard_task_list_company_office =
      const IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      fastforward_clock__time_clock_reset_stopwatch_circle_measure_loading =
      const IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData film_slate__pictures_photo_film_slate =
      const IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData filter_2__funnel_filter_angle_oil =
      const IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData flash_2__flash_power_connect_charge_electricity_lightning =
      const IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData flash_off__flash_power_connect_charge_off_electricity_lightning =
      const IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData floppy_disk__disk_floppy_electronics_device_disc_computer_storage =
      const IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      flower__photos_photo_picture_camera_photography_pictures_flower_image =
      const IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData folder_delete__remove_minus_folder_subtract_delete =
      const IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      fork_spoon__fork_spoon_food_dine_cook_utensils_eat_restaurant_dining_kitchenware =
      const IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData full_screen =
      const IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData graduation_cap__graduation_cap_education =
      const IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData graph__analytics_business_product_graph_data_chart_analysis =
      const IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData graph_arrow_decrease__down_stats_graph_descend_right_arrow =
      const IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData graph_arrow_increase__ascend_growth_up_arrow_stats_graph_right_grow =
      const IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      graph_bar_increase__up_product_performance_increase_arrow_graph_business_chart =
      const IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      graph_dot__product_data_bars_analysis_analytics_graph_business_chart_dot =
      const IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData group_meeting_call__group_meeting_call_work =
      const IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData heart__reward_social_rating_media_heart_it_like_favorite_love =
      const IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData hearts_symbol__entertainment_gaming_card_hearts_symbol =
      const IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      help_question_1__circle_faq_frame_help_info_mark_more_query_question =
      const IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData home_3__home_house_roof_shelter =
      const IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      horizontal_menu_circle__navigation_dots_three_circle_button_horizontal_menu =
      const IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData inbox_tray_1__mail_email_outbox_drawer_empty_open_inbox_arrow_down =
      const IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData inbox_tray_2__mail_email_outbox_drawer_empty_open_inbox_arrow_up =
      const IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData invisible_1__disable_eye_eyeball_hide_off_view =
      const IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData invisible_2 =
      const IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData keyboard__keyboard_device_electronics_dvorak_qwerty =
      const IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      keyboard_virtual__remote_device_electronics_qwerty_keyboard_virtual_interface =
      const IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      keyboard_wireless_2__remote_device_wireless_electronics_qwerty_keyboard_bluetooth =
      const IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      landscape_2__photos_photo_landscape_picture_photography_camera_pictures_image =
      const IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData lightbulb__lighting_light_incandescent_bulb_lights =
      const IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData like_1__reward_social_up_rating_media_like_thumb_hand =
      const IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData link_chain__create_hyperlink_link_make_unlink_connection_chain =
      const IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData location_compass_1__arrow_compass_location_gps_map_maps_point =
      const IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData location_pin_3__navigation_map_maps_pin_gps_location =
      const IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData login_1__arrow_enter_frame_left_login_point_rectangle =
      const IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData logout_1__arrow_exit_frame_leave_logout_rectangle_right =
      const IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData magic_wand_2__design_magic_star_supplies_tool_wand =
      const IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData magnifying_glass__glass_search_magnifying =
      const IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData mail_send_email_message__send_email_paper_airplane_deliver =
      const IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData mail_send_envelope__envelope_email_message_unopened_sealed_close =
      const IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData mail_send_reply_all__email_message_reply_all_actions_action_arrow =
      const IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData megaphone_2__bullhorn_loud_megaphone_share_speaker_transmit =
      const IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData module_puzzle_1__code_puzzle_module_programming_plugin_piece =
      const IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData mouse_wireless__remote_wireless_device_electronics_mouse_computer =
      const IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData mouse_wireless_1__remote_wireless_device_electronics_mouse_computer =
      const IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      music_equalizer__music_audio_note_wave_sound_equalizer_entertainment =
      const IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      navigation_arrow_off__compass_arrow_map_bearing_navigation_maps_heading_gps_off_disable =
      const IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      navigation_arrow_on__compass_arrow_map_bearing_navigation_maps_heading_gps_off_disable =
      const IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData new_file__empty_common_file_content =
      const IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData new_folder__empty_folder =
      const IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData new_sticky_note__empty_common_file =
      const IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData next__next_arrow_right_keyboard =
      const IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData no_poverty =
      const IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      notification_alarm_2__android_phone_mobile_device_smartphone_iphone_alert_bell_alarm =
      const IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData number_1 =
      const IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData number_2 =
      const IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData office_worker__office_worker_human_resources =
      const IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData open_book__content_books_book_open =
      const IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      orientation_landscape__photos_photo_orientation_landscape_picture_photography_camera_pictures_image =
      const IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      outgoing_call__android_phone_mobile_device_smartphone_iphone_ringing_outgoing_call =
      const IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      padlock_square_1__combination_combo_lock_locked_padlock_secure_security_shield_keyhole =
      const IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData paperclip_1__attachment_link_paperclip_unlink =
      const IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData party_popper__hobby_entertainment_party_popper_confetti_event =
      const IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData pencil__change_edit_modify_pencil_write_writing =
      const IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData phone__android_phone_mobile_device_smartphone_iphone =
      const IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData phone_mobile_phone__android_phone_mobile_device_smartphone_iphone =
      const IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      phone_qr__android_phone_mobile_device_smartphone_iphone_qr_code_scan =
      const IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      phone_ringing_1__android_phone_mobile_device_smartphone_iphone_ringing_incoming_call =
      const IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData qr_code__codes_tags_code_qr =
      const IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData rainbow__nature_arch_rain_colorful_rainbow_curve_half_circle =
      const IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData recycle_bin_2__remove_delete_empty_bin_trash_garbage =
      const IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData return_2__arrow_return_enter_keyboard =
      const IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      ringing_bell_notification__notification_vibrate_ring_sound_alarm_alert_bell_noise =
      const IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData screen_1__screen_device_electronics_monitor_diplay_computer =
      const IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData share_link__share_transmit =
      const IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData shield_2__shield_protection_security_defend_crime_war_cover =
      const IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData small_screen =
      const IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData smoking_area =
      const IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData sort_descending =
      const IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData star_1__reward_rating_rate_social_star_media_favorite_like_stars =
      const IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      star_2__reward_rating_rate_social_star_media_favorite_like_stars_spark =
      const IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData star_badge__ribbon_reward_like_social_rating_media =
      const IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData startup__shop_rocket_launch_startup =
      const IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      street_sign__crossroad_street_sign_metaphor_directions_travel_places =
      const IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      subtract_1__button_delete_buttons_subtract_horizontal_remove_line_add_mathematics_math_minus =
      const IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      subtract_circle__delete_add_circle_subtract_button_buttons_remove_mathematics_math_minus =
      const IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      subtract_square__subtract_buttons_remove_add_button_square_delete_mathematics_math_minus =
      const IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData target__shop_bullseye_arrow_target =
      const IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData target_3__shop_bullseye_shooting_target =
      const IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData task_list__task_list_work =
      const IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      telescope__science_experiment_star_gazing_sky_night_space_universe_astronomy_astronomy =
      const IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData test_tube__science_experiment_lab_chemistry_test_tube_solution =
      const IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      toilet_sign_man_woman_2__toilet_sign_restroom_bathroom_user_human_person =
      const IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData traffic_cone__street_sign_traffic_cone_road =
      const IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData tree_2__nature_tree_plant_circle_round_park =
      const IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData tree_3__nature_tree_plant_cloud_shape_park =
      const IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData trending_content__lit_flame_torch_trending =
      const IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      triangle_flag__navigation_map_maps_flag_gps_location_destination_goal =
      const IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      upload_circle__arrow_circle_download_internet_network_server_up_upload =
      const IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData upload_file =
      const IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      user_add_plus__actions_add_close_geometric_human_person_plus_single_up_user =
      const IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData user_circle_single__circle_geometric_human_person_single_user =
      const IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData user_identifier_card =
      const IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData user_multiple_group__close_geometric_human_multiple_person_up_user =
      const IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData user_profile_focus__close_geometric_human_person_profile_focus_user =
      const IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      user_single_neutral_male__close_geometric_human_person_single_up_user_male =
      const IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData video_swap_camera =
      const IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData visible__eye_eyeball_open_view =
      const IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData voice_mail__mic_audio_mike_music_microphone =
      const IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData voice_mail_off__mic_audio_mike_music_microphone_mute_off =
      const IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      volume_down__speaker_down_volume_control_audio_music_decrease_entertainment =
      const IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      volume_level_high__speaker_high_volume_control_audio_music_entertainment =
      const IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      volume_level_low__volume_speaker_lower_down_control_music_low_audio_entertainment =
      const IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData volume_level_off__volume_speaker_control_music_audio_entertainment =
      const IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      volume_mute__speaker_remove_volume_control_audio_music_mute_off_cross_entertainment =
      const IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      volume_off__speaker_music_mute_volume_control_audio_off_mute_entertainment =
      const IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData warning_triangle__frame_alert_warning_triangle_exclamation_caution =
      const IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData watch_1__device_timepiece_cirle_electronics_face_blank_watch_smart =
      const IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      watch_circle_time__device_timepiece_circle_watch_round_time_clock_analog =
      const IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData wave_signal__heart_line_beat_square_graph_stats =
      const IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData web__server_world_internet_earth_www_globe_worldwide_web_network =
      const IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData webcam__webcam_camera_future_tech_chat_skype_technology_video =
      const IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData webcam_video__work_video_meeting_camera_company_conference_office =
      const IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData
      webcam_video_off__work_video_meeting_camera_company_conference_office_off =
      const IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData wrench__crescent_tool_construction_tools_wrench_setting_edit_adjust =
      const IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData zero_hunger =
      const IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
